(cl:defpackage sensor_controller-srv
  (:use )
  (:export
   "INTEGRAL"
   "<INTEGRAL-REQUEST>"
   "INTEGRAL-REQUEST"
   "<INTEGRAL-RESPONSE>"
   "INTEGRAL-RESPONSE"
   "RECORD"
   "<RECORD-REQUEST>"
   "RECORD-REQUEST"
   "<RECORD-RESPONSE>"
   "RECORD-RESPONSE"
   "TARE"
   "<TARE-REQUEST>"
   "TARE-REQUEST"
   "<TARE-RESPONSE>"
   "TARE-RESPONSE"
   "TARED"
   "<TARED-REQUEST>"
   "TARED-REQUEST"
   "<TARED-RESPONSE>"
   "TARED-RESPONSE"
  ))

