// Generated by gencpp from file sensor_controller/Integral.msg
// DO NOT EDIT!


#ifndef SENSOR_CONTROLLER_MESSAGE_INTEGRAL_H
#define SENSOR_CONTROLLER_MESSAGE_INTEGRAL_H

#include <ros/service_traits.h>


#include <sensor_controller/IntegralRequest.h>
#include <sensor_controller/IntegralResponse.h>


namespace sensor_controller
{

struct Integral
{

typedef IntegralRequest Request;
typedef IntegralResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Integral
} // namespace sensor_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_controller::Integral > {
  static const char* value()
  {
    return "bbb7ba84302b6f35af5466a95cd7ac90";
  }

  static const char* value(const ::sensor_controller::Integral&) { return value(); }
};

template<>
struct DataType< ::sensor_controller::Integral > {
  static const char* value()
  {
    return "sensor_controller/Integral";
  }

  static const char* value(const ::sensor_controller::Integral&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_controller::IntegralRequest> should match
// service_traits::MD5Sum< ::sensor_controller::Integral >
template<>
struct MD5Sum< ::sensor_controller::IntegralRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_controller::Integral >::value();
  }
  static const char* value(const ::sensor_controller::IntegralRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_controller::IntegralRequest> should match
// service_traits::DataType< ::sensor_controller::Integral >
template<>
struct DataType< ::sensor_controller::IntegralRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_controller::Integral >::value();
  }
  static const char* value(const ::sensor_controller::IntegralRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_controller::IntegralResponse> should match
// service_traits::MD5Sum< ::sensor_controller::Integral >
template<>
struct MD5Sum< ::sensor_controller::IntegralResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_controller::Integral >::value();
  }
  static const char* value(const ::sensor_controller::IntegralResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_controller::IntegralResponse> should match
// service_traits::DataType< ::sensor_controller::Integral >
template<>
struct DataType< ::sensor_controller::IntegralResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_controller::Integral >::value();
  }
  static const char* value(const ::sensor_controller::IntegralResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_CONTROLLER_MESSAGE_INTEGRAL_H
