// Generated by gencpp from file sensor_controller/RecordRequest.msg
// DO NOT EDIT!


#ifndef SENSOR_CONTROLLER_MESSAGE_RECORDREQUEST_H
#define SENSOR_CONTROLLER_MESSAGE_RECORDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_controller
{
template <class ContainerAllocator>
struct RecordRequest_
{
  typedef RecordRequest_<ContainerAllocator> Type;

  RecordRequest_()
    : start(false)  {
    }
  RecordRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::sensor_controller::RecordRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_controller::RecordRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RecordRequest_

typedef ::sensor_controller::RecordRequest_<std::allocator<void> > RecordRequest;

typedef boost::shared_ptr< ::sensor_controller::RecordRequest > RecordRequestPtr;
typedef boost::shared_ptr< ::sensor_controller::RecordRequest const> RecordRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_controller::RecordRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_controller::RecordRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_controller::RecordRequest_<ContainerAllocator1> & lhs, const ::sensor_controller::RecordRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_controller::RecordRequest_<ContainerAllocator1> & lhs, const ::sensor_controller::RecordRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_controller::RecordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_controller::RecordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_controller::RecordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_controller::RecordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_controller::RecordRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_controller::RecordRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_controller::RecordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::sensor_controller::RecordRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_controller::RecordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_controller/RecordRequest";
  }

  static const char* value(const ::sensor_controller::RecordRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_controller::RecordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start\n"
;
  }

  static const char* value(const ::sensor_controller::RecordRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_controller::RecordRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecordRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_controller::RecordRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_controller::RecordRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_CONTROLLER_MESSAGE_RECORDREQUEST_H
