// Generated by gencpp from file sensor_controller/TaredResponse.msg
// DO NOT EDIT!


#ifndef SENSOR_CONTROLLER_MESSAGE_TAREDRESPONSE_H
#define SENSOR_CONTROLLER_MESSAGE_TAREDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_controller
{
template <class ContainerAllocator>
struct TaredResponse_
{
  typedef TaredResponse_<ContainerAllocator> Type;

  TaredResponse_()
    : success(false)  {
    }
  TaredResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::sensor_controller::TaredResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_controller::TaredResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TaredResponse_

typedef ::sensor_controller::TaredResponse_<std::allocator<void> > TaredResponse;

typedef boost::shared_ptr< ::sensor_controller::TaredResponse > TaredResponsePtr;
typedef boost::shared_ptr< ::sensor_controller::TaredResponse const> TaredResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_controller::TaredResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_controller::TaredResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_controller::TaredResponse_<ContainerAllocator1> & lhs, const ::sensor_controller::TaredResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_controller::TaredResponse_<ContainerAllocator1> & lhs, const ::sensor_controller::TaredResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_controller::TaredResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_controller::TaredResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_controller::TaredResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_controller::TaredResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_controller::TaredResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_controller::TaredResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_controller::TaredResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sensor_controller::TaredResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_controller::TaredResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_controller/TaredResponse";
  }

  static const char* value(const ::sensor_controller::TaredResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_controller::TaredResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::sensor_controller::TaredResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_controller::TaredResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaredResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_controller::TaredResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_controller::TaredResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_CONTROLLER_MESSAGE_TAREDRESPONSE_H
