// Generated by gencpp from file sensor_controller/TaredRequest.msg
// DO NOT EDIT!


#ifndef SENSOR_CONTROLLER_MESSAGE_TAREDREQUEST_H
#define SENSOR_CONTROLLER_MESSAGE_TAREDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_controller
{
template <class ContainerAllocator>
struct TaredRequest_
{
  typedef TaredRequest_<ContainerAllocator> Type;

  TaredRequest_()
    : tared(false)  {
    }
  TaredRequest_(const ContainerAllocator& _alloc)
    : tared(false)  {
  (void)_alloc;
    }



   typedef uint8_t _tared_type;
  _tared_type tared;





  typedef boost::shared_ptr< ::sensor_controller::TaredRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_controller::TaredRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TaredRequest_

typedef ::sensor_controller::TaredRequest_<std::allocator<void> > TaredRequest;

typedef boost::shared_ptr< ::sensor_controller::TaredRequest > TaredRequestPtr;
typedef boost::shared_ptr< ::sensor_controller::TaredRequest const> TaredRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_controller::TaredRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_controller::TaredRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_controller::TaredRequest_<ContainerAllocator1> & lhs, const ::sensor_controller::TaredRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tared == rhs.tared;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_controller::TaredRequest_<ContainerAllocator1> & lhs, const ::sensor_controller::TaredRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor_controller::TaredRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_controller::TaredRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_controller::TaredRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_controller::TaredRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_controller::TaredRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_controller::TaredRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_controller::TaredRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fd703c0ee4e7e6a4afe6895bfa94ce9";
  }

  static const char* value(const ::sensor_controller::TaredRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fd703c0ee4e7e6aULL;
  static const uint64_t static_value2 = 0x4afe6895bfa94ce9ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_controller::TaredRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_controller/TaredRequest";
  }

  static const char* value(const ::sensor_controller::TaredRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_controller::TaredRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool tared\n"
;
  }

  static const char* value(const ::sensor_controller::TaredRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_controller::TaredRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tared);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaredRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_controller::TaredRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_controller::TaredRequest_<ContainerAllocator>& v)
  {
    s << indent << "tared: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tared);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_CONTROLLER_MESSAGE_TAREDREQUEST_H
